=== jfritz124/XML/rechnung.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:simpleType name="MailPattern">
        <xs:restriction base="xs:string">
            <xs:maxLength value="255"/>
            <xs:pattern value=".+@[A-z0-9]+\.[A-z]+"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:element name="FRechnung">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Rechnung" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:normalizedString" name="Tag" minOccurs="0"/>
                            <xs:element name="Kontakt">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Empfaenger">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Adresse">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element type="xs:normalizedString" name="Anrede" minOccurs="0"/>
                                                                <xs:element type="xs:normalizedString" name="Name"/>
                                                                <xs:element type="xs:normalizedString" name="Strasse"/>
                                                                <xs:element type="xs:normalizedString" name="Hausnummer"/>
                                                                <xs:element type="xs:int" name="PLZ"/>
                                                                <xs:element type="xs:normalizedString" name="Ort"/>
                                                                <xs:element type="xs:int" name="Tel" minOccurs="0"/>
                                                                <xs:element type="xs:int" name="Fax" minOccurs="0"/>
                                                            </xs:sequence>
                                                            <xs:attribute type="MailPattern" name="Mail"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="Sender">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Adresse">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element type="xs:normalizedString" name="Anrede" minOccurs="0"/>
                                                                <xs:element type="xs:normalizedString" name="Name"/>
                                                                <xs:element type="xs:normalizedString" name="Strasse"/>
                                                                <xs:element type="xs:normalizedString" name="Hausnummer"/>
                                                                <xs:element type="xs:int" name="PLZ"/>
                                                                <xs:element type="xs:normalizedString" name="Ort"/>
                                                                <xs:element type="xs:int" name="Tel" minOccurs="0"/>
                                                                <xs:element type="xs:int" name="Fax" minOccurs="0"/>
                                                            </xs:sequence>
                                                            <xs:attribute type="MailPattern" name="Mail"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element type="xs:normalizedString" name="Steuernummer"/>
                            <xs:element type="xs:date" name="DatumAusstellung"/>
                            <xs:element type="xs:normalizedString" name="RechnungsNummer"/>
                            <xs:element name="Betrag">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:float" name="Brutto"/>
                                        <xs:element type="xs:float" name="Netto"/>
                                        <xs:element type="xs:float" name="Mwst"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Positionen">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Pos" maxOccurs="unbounded" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element type="xs:int" name="Menge"/>
                                                    <xs:element type="xs:normalizedString" name="Produkt"/>
                                                    <xs:element type="xs:float" name="Preis"/>
                                                    <xs:element type="xs:byte" name="Mehrwertsteuer"/>
                                                </xs:sequence>
                                                <xs:attribute type="xs:int" name="PosNummer" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Footer">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:normalizedString" name="USTNummer"/>
                                        <xs:element name="KontoBank" maxOccurs="unbounded" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element type="xs:normalizedString" name="BankName"/>
                                                    <xs:element type="xs:int" name="KontoNummer" minOccurs="0"/>
                                                    <xs:element type="xs:normalizedString" name="IBAN"/>
                                                    <xs:element type="xs:normalizedString" name="BIC"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="Bitcoin">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element type="xs:normalizedString" name="BitAdresse"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== jfritz124/XML/aufgabe3.xml
<?xml version="1.0" encoding="UTF-8" ?>

<FRechnung xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="rechnung.xsd">
    <Rechnung>
        <Tag></Tag>
        <Kontakt>
            <Empfaenger>
                <Adresse>
                    <Anrede>Dr. med.</Anrede>
                    <Name>Cyprian Zottel</Name>
                    <Strasse>Soddelstrudel</Strasse>
                    <Hausnummer>5a</Hausnummer>
                    <PLZ>13023</PLZ>
                    <Ort>Zotenheim</Ort>
                </Adresse>
            </Empfaenger>
            <Sender></Sender>
        </Kontakt>
        <Positionen>
            <Pos PosNummer = "1">
                <Menge>3</Menge>
                <Produkt>Grippemittel "Tumifla"</Produkt>
                <Preis>360.0</Preis>
                <Mehrwertsteuer>19</Mehrwertsteuer>
            </Pos>
            <Pos PosNummer = "2">
                <Menge></Menge>
                <Produkt>Beratung pauschal</Produkt>
                <Preis>50.0</Preis>
                <Mehrwertsteuer>19</Mehrwertsteuer>
            </Pos>
            <Pos PosNummer = "3">
                <Menge>2</Menge>
                <Produkt>Abführmittel "Wech damit" pro Liter</Produkt>
                <Preis>199.98</Preis>
                <Mehrwertsteuer>19</Mehrwertsteuer>
            </Pos>
            <Pos PosNummer = "4">
                <Menge>2</Menge>
                <Produkt>Energieriegel "Sato"</Produkt>
                <Preis>11.96</Preis>
                <Mehrwertsteuer>7</Mehrwertsteuer>
            </Pos>
        </Positionen>
        <Betrag>
            <Brutto>962.22</Brutto>
            <Netto>490,22</Netto>
            <Mwst>116,74</Mwst>
        </Betrag>
        <Footer>
            <USTNummer>DE333666999</USTNummer>
        </Footer>
    </Rechnung>


    <Rechnung>
        <Tag>Kleintier Meier - Kleintierhandel</Tag>
        <Kontakt>
            <Empfaenger></Empfaenger>
            <Sender>
                <Adresse>
                    <Name>Kleintier Meier GmbH</Name>
                    <Strasse>Meierring</Strasse>
                    <Hausnummer>3</Hausnummer>
                    <PLZ>81828</PLZ>
                    <Ort>Machthausen</Ort>
                    <Tel>0777/987987</Tel>
                    <Fax>0777/987789</Fax>
                    <Mail>klein.meier@tiere.de</Mail>
                </Adresse>
            </Sender>
        </Kontakt>
        <RechnungsNummer>657321</RechnungsNummer>
        <Steuernummer>88123/82822</Steuernummer>
        <DatumAusstellung>2017-01-15</DatumAusstellung>
        <Positionen></Positionen>
        <Betrag>
            <Brutto>962.22</Brutto>
        </Betrag>
        <Footer>
        </Footer>
    </Rechnung>

    <Rechnung>
        <Kontakt>
            <Sender>
                <Adresse>
                    <Name>Bestattung Unterberg</Name>
                    <Strasse>Oberbergweg</Strasse>
                    <Hausnummer>5</Hausnummer>
                    <PLZ>43210</PLZ>
                    <Ort>Ultursingen</Ort>
                    <Tel>0478777555</Tel>
                    <Mail>unter@berg.de</Mail>
                </Adresse>
            </Sender>
            <Empfaenger>
                <Adresse>
                    <Anrede>Familie</Anrede>
                    <Name>Urmel</Name>
                    <Strasse>Ulturenstrasse</Strasse>
                    <Hausnummer>764</Hausnummer>
                    <PLZ>43210</PLZ>
                    <Ort>Ultursingen</Ort>
                </Adresse>
            </Empfaenger>
        </Kontakt>
        <Steuernummer>DE987654321</Steuernummer>
        <DatumAusstellung>2017-10-19</DatumAusstellung>
        <RechnungsNummer>89321311</RechnungsNummer>
        <Betrag>
            <Brutto>738.23</Brutto>
            <Netto>878.49</Netto>
            <Mwst>140.26</Mwst>
        </Betrag>
        <Positionen>
            <Pos PosNummer = "1">
                <Menge>1</Menge>
                <Produkt>Urne, Eiche massiv</Produkt>
                <Preis>299.99</Preis>
                <Mehrwertsteuer>19</Mehrwertsteuer>
            </Pos>
            <Pos PosNummer = "2">
                <Menge>1</Menge>
                <Produkt>Überführung Krematorium Feuerbach</Produkt>
                <Preis>349.0</Preis>
                <Mehrwertsteuer>19</Mehrwertsteuer>
            </Pos>
            <Pos PosNummer = "3">
                <Menge>1</Menge>
                <Produkt>Dekoration</Produkt>
                <Preis>149.5</Preis>
                <Mehrwertsteuer>19</Mehrwertsteuer>
            </Pos>
            <Pos PosNummer = "3">
                <Menge>1</Menge>
                <Produkt>Dekoration</Produkt>
                <Preis>149.5</Preis>
                <Mehrwertsteuer>19</Mehrwertsteuer>
            </Pos>
            <Pos PosNummer = "4">
                <Menge>40</Menge>
                <Produkt>Trauerkarten</Produkt>
                <Preis>80.0</Preis>
                <Mehrwertsteuer>19</Mehrwertsteuer>
            </Pos>
        </Positionen>
        <Footer>
            <USTNummer>DE333666999</USTNummer>
            <KontoBank>
                <BankName>UBS Zürich</BankName>
                <KontoNummer>75847683</KontoNummer>
                <IBAN>DE16660501010077889911</IBAN>
                <BIC>UBSWCHZH80H</BIC>
            </KontoBank>
            <Bitcoin>
                <BitAdresse>1P82rBiJHDFSav2QrKx1bvdDRVh5QnGkkZ</BitAdresse>
            </Bitcoin>
        </Footer>
    </Rechnung>
</FRechnung>
